GREET = 'greet'
GOODBYE = 'goodbye'
TICKET_CLASS = 'ticket_class'
ORIGIN = 'origin'
DESTINATION = 'destination'
DATE = 'date'
RETURN_DATE = 'return_date'
TRAVELERS_NUMBER = 'travelersNumber'
ADULTS = 'adults'
CHILDREN = 'children'
INFANTS = 'infants'


client_id='GPz1XnJDneocc2mri9GyJbp259cCRrbn'
client_secret='8pUkGxmd4zv5G9FM'
